package Error.Exception_try_Catch;

public class try_catch {

    public static void main(String[] args){
        int[] myNum = {1,2,3};
        System.out.println(myNum[10]);

//        Note: ArrayIndexOutOfBoundsException occurs when you try to access an index number that does not exist.
    }
}


/*
* try{}
* catch(Exception e) {}
*
* */